### ISSUE TITLE
Implement local file upload feature

### ISSUE THREAD

**Issue by vivonk** [scorelab/Bassa#478] opened 2018-08-01 18:18 UTC
Generalize Bassa for every possible use. As user currently add a url to download. What if they want to share files with other users which are in their local.
## Expected Behavior
Implement a local file upload feature so that users can share content in a secure and easiest way.

## Possible Solution

A simple/ compressed file upload architecture on front end and back end.

**Comment by surana-mudit** [comment] 2018-09-21 21:00
Hi @vivonk I am new to this organization and project, and I would like to start with this issue.
Can you please help me in getting started with the issue.

**Comment by vivonk** [comment] 2018-09-21 21:05
Thanks, @surana-mudit for showing your interest. So the thing is Bassa only download files from links. We have to implement a feature which can upload the file from local pc to the server. First, go to read me and setup Bassa. It might not be a beginner task so if you can explore the codebase first then you will understand better. 
One more thing, learn it how we can upload files from client to server using flask :smile:

**Comment by phoenixking25** [comment] 2018-09-29 18:37
Ok thanks right now i am not working on this, but that point what i asked can help others or i can also work later on this. :)

**Comment by vivonk** [comment] 2018-09-29 18:38
It's up to you @phoenixking25 :smile:

**Comment by VibhorCodecianGupta** [comment] 2018-09-30 10:35
Hello, I am currently working on this. Will be updating on the progress or in case I drop the issue.

**Comment by phoenixking25** [comment] 2018-09-30 10:56
Sure no problem

**Comment by VibhorCodecianGupta** [comment] 2019-08-14 09:17
Duplicate of #802

**Closed by VibhorCodecianGupta** 2019-08-14 09:17 UTC
